name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js 環境のセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 依存関係のインストール
      - name: Install dependencies
        run: npm install

      # Next.js をビルドして静的サイトを生成
      - name: Build and export Next.js
        run: npm run export

      # エクスポート内容の確認
      - name: Show build output
        run: ls -R ./docs

      # .nojekyll ファイルを追加
      - name: Add .nojekyll file
        run: echo '' > docs/.nojekyll

      # GitHub Pages にデプロイ
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false          # true 既存ファイルを保持して上書きする false すべてのファイルを上書き
          allow_empty_commit: true  # 空のコミットも許可